### ISSUE TITLE
consider adding annotation option

### ISSUE THREAD

**Issue by sarahcd** [movestore/FilterData-bySeason#4]
We have requests to add a 'season' assignment to the dataframe. Maybe this app could be expanded to do this? Similar to what was done in the Filter by Day or Night App, but in this case we would probably want to allow multiple (up to 4?) season breakpoints.

**Comment by andreakoelzsch** [comment]
annotation is now possible, but only for one time interval season. I updated it a bit, so that the app can be run several times for different seasons. Namely, that the season name will be added to the existing column "season" if it is there.
