### ISSUE TITLE
Empty output if "Split tracks by season" is unchecked

### ISSUE THREAD

**Issue by sarahcd** [movestore/FilterData-bySeason#6]
The "Split tracks by season" setting is great! However, if I do not select it (default), I get no results at all. It produces an rds file, but causes an error in the subsequent app and looks empty in the cargo agent:
![image](https://github.com/movestore/FilterData-bySeason/assets/15783614/bf4d591b-eb41-4147-8d5c-5000053eddd6)

I shared a workflow as an example. Did not try it yet across other input data.

**Comment by andreakoelzsch** [comment]
thanks Sarah, Bart is already giving me alternative ways of working this out. Let me finish another App for Ashley first, then I will come back to it.

**Comment by andreakoelzsch** [comment]
I reworked the App with some help from Bart, it should work now. Please try

**Comment by sarahcd** [comment]
Nice! I ran it with various settings and it no longer gives an error. I didn't inspect the output closely but will review it for the workflows I'm building and report back if needed.
