### ISSUE TITLE
Are years still appended to the track name?

### ISSUE THREAD

**Issue by sarahcd** [movestore/FilterData-bySeason#7]
Testing with the new app, the year is no longer appended in the track name. Instead they are numbered.
Ideally the year can still be included in the name if tracks are split by season.
![image](https://github.com/movestore/FilterData-bySeason/assets/15783614/7ff3347d-ab1b-4cff-8515-356f2a4db4a6)

**Comment by andreakoelzsch** [comment]
this was rather complicated to me, so was not in the first version. done now. update of the app following in the coming hours
